server:
  port: 80
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/plain,text/css,application/x-javascript
spring:
  application:
    name: fa-admin-dev
  profiles:
    active: dev
  web:
    resources:
      static-locations: classpath:public/,classpath:static/,file:static/,file:public/,classpath:/resources,classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/
  # https://blog.csdn.net/weixin_71454352/article/details/140207880
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DBNAME:faber_admin}?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    druid:
      name: fa-admin-dev
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin@1234

  # spring boot admin client
  boot:
    admin:
      client:
        url: http://localhost:8001
        username: admin
        password: 103Tiger
        instance:
          service-base-url: http://localhost

  #redis-cache 相关，这里是springboot2.x的redis配置，与下面ace-cache的配置重复，但是都不能删除，后续要改进
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 2000
      password: ~
      prefix: fa-admin # 默认key前缀
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  #      location: /tmp

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 123456
easy-es:
  enable: true #默认为true,若为false则认为不启用本框架
  address : 127.0.0.1:9200 # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
  username: elastic #若无 则可省略此行配置
  password: 123456 #若无 则可省略此行配置
  global-config:
    print-dsl: true
    db-config:
      index-prefix: fa-ai-dev-

dromara:
  x-file-storage: #文件存储配置
    default-platform: local-plus-1 #默认使用的存储平台
    thumbnail-suffix: ".min.png" #缩略图后缀，例如【.min.jpg】【.png】
    #对应平台的配置写在这里，注意缩进要对齐
    local-plus: # 本地存储升级版，不使用的情况下可以不写
      - platform: local-plus-1 # 存储平台标识
        enable-storage: true #启用存储
        enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: "" # 访问域名，例如：“http://127.0.0.1:8030/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: local-plus/ # 基础路径
        path-patterns: /** # 访问路径
        storage-path: D:/Temp/file/ # 存储路径

# sa-token 配置
sa-token:
  # token 名称 (同时也是 cookie 名称)
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# Mybatis-Plus，在MybatisPlusConfig中代码配置
#mybatis-plus:
#  # Maven 多模块项目的扫描路径需以 classpath*: 开头 （即加载多个 jar 包下的 XML 文件）
#  mapper-locations: classpath*:/mapper/**/*.xml

# 配置swagger
swagger:
  enabled: true
  base-package: com.faber
  title: fa-admin
  version: 1.0.0.SNAPSHOTProcessDiagramGenerator
  description: 管理后端服务
  contact:
    name: admin

# spring-boot-admin监控服务对接配置
management:
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ./log/springboot.admin.log
  endpoints:
    web:
      base-path: /apij/actuator
      exposure:
        include: "*"

# 声明式HTTP客户端框架
forest:
  backend: okhttp3 # 配置后端HTTP API为 okhttp3
  connect-timeout: 10000
  read-timeout: 100000
  timeout: 60000
#  variables:
#    api: https://xxx.com/api      # pconline ip地址查询

# 一些默认配置
fa:
  setting:
    # TODO 删除JWT配置（使用sa-token替代）
    jwt:
      tokenHeader: Authorization
      # token失效时间(单位秒)，24小时
      expire: 86400
      # secret的长度需要大于18
      secret: 2022#8m3n2@fa-admin
    # 安全配置
    safety:
      # 是否校验URL、body的签名完整性
      intact: false
      # 和前端统一的签名密钥，前端配置地址为：frontend/apps/admin/.env.development (.env.production)
      secret: 103103
    # API配置
    api:
      tokenApiHeader: FaApiToken
    # APP配置
    app:
      # 设备首次注册后是否允许访问
      deviceDefaultAllow: true
    file:
      # 系统文件存储方式: local-本地存储/qiniu-七牛云
      saveType: local
      # 增加一层最前置路径，可以用于区分不同环境
      prefix: dev
    # 七牛云存储
    qiniu:
      accessKey: xxx
      secretKey: xxx
      bucket: xxx
      host: http://xxx
    # 高德地图SDK
    amap:
      key: xx
    # 加密，aes秘钥长度必须为16位
    aes:
      key: 2345ASDC89ABCSEQ
      salt: DYgaREIsYrj24QxN
    # 系统设置
    config:
      # 系统启动时执行数据库初始化脚本
      startDbInitOnBoot: true
      # 系统启动时扫描任务class并启动
      startJobsOnBoot: true
    url:
      phpRedisAdmin: http://127.0.0.1:8182
      socketUrl: 127.0.0.1:8081
      kkFileView: http://127.0.0.1:8012
    # onlyoffice在线编辑office文件支持
    onlyoffice:
      # ONLYOFFICE_SERVER，返回给前端获取api
      onlyofficeServer: http://127.0.0.1:1234/
      # 本服务提供给onlyoffice回调的服务器地址
      callbackServer: http://127.0.0.1/
      # docservice中配置jwt secret
      docserviceSecret: faberJWT1256
      # docservice中配置token的Header Key
      docserviceHeader: Authorization
      fileFillformsDocs: .oform|.docx
      fileViewedDocs: .pdf|.djvu|.xps|.oxps
      fileEditedDocs: .docx|.xlsx|.csv|.pptx|.txt|.docxf
      fileConvertDocs: .docm|.dotx|.dotm|.dot|.doc|.odt|.fodt|.ott|.xlsm|.xlsb|.xltx|.xltm|.xlt|.xls|.ods|.fods|.ots|.pptm|.ppt|.ppsx|.ppsm|.pps|.potx|.potm|.pot|.odp|.fodp|.otp|.rtf|.mht|.html|.htm|.xml|.epub|.fb2
    threadPoolConfig:
      corePoolSize: 5
      maxPoolSize: 20
      queueCapacity: 20
      keepAliveSeconds: 200
      threadNamePrefix: my-fa-thread-
      waitForJobsToCompleteOnShutdown: true
      awaitTerminationSeconds: 60

# --------------------------------------------- 短信模板-阿里云 ---------------------------------------------
aliyun:
  sms:
    regionId: cn-hangzhou
    accessKeyId: xx
    secret: xx
    signName: xx
    # 短信模板配置
    smsConfig:
      # 短信验证码
      SMD_CODE:
        smsCode: SMS_xxx
        template: "您的验证码为：${code}，该验证码5分钟内有效，请勿泄露于他人。"
        keys:
          - code
