import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { relative as relativePath, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import react from '@vitejs/plugin-react';
import { defineConfig, loadEnv, type Plugin } from 'vite';
import Pages from 'vite-plugin-pages';

const portalRoot = fileURLToPath(new URL('.', import.meta.url));
const profileNamePattern = /^[a-z][a-z0-9-]*$/;

function resolvePortalProfile(profileName: string): string {
  if (!profileNamePattern.test(profileName)) {
    throw new Error(`PORTAL_PROFILE "${profileName}" 命名无效，必须使用 kebab-case`);
  }

  const profilePath = resolvePath(portalRoot, 'app', 'profiles', `${profileName}.ts`);
  if (!existsSync(profilePath)) {
    throw new Error(`PORTAL_PROFILE "${profileName}" 不存在：${profilePath}`);
  }
  return profilePath;
}

function generateSelectedProfileModule(profileName: string): void {
  const generatedDirectory = resolvePath(portalRoot, '.portal');
  const generatedFile = resolvePath(generatedDirectory, 'selected-profile.ts');
  const source = `// Generated by vite.config.ts. Do not edit.\nexport { default } from '../app/profiles/${profileName}';\n`;

  mkdirSync(generatedDirectory, { recursive: true });
  if (!existsSync(generatedFile) || readFileSync(generatedFile, 'utf8') !== source) {
    writeFileSync(generatedFile, source, 'utf8');
  }
}

function portalModuleGraphPlugin(): Plugin {
  return {
    name: 'fa-portal-module-graph',
    apply: 'build',
    writeBundle(options, bundle) {
      if (!options.dir) return;

      const modules = [
        ...new Set(
          Object.values(bundle).flatMap((output) =>
            output.type === 'chunk'
              ? Object.keys(output.modules).map((moduleId) => {
                  const sourceFile = moduleId.split('?', 1)[0];
                  return sourceFile.startsWith(portalRoot) ? relativePath(portalRoot, sourceFile) : sourceFile;
                })
              : [],
          ),
        ),
      ].sort();
      const reportFile = resolvePath(options.dir, 'client-module-graph.json');
      writeFileSync(reportFile, `${JSON.stringify({ modules }, null, 2)}\n`, 'utf8');
    },
  };
}

function flattenPageRoutes(routes: any[], parentPath = ''): any[] {
  return routes.flatMap((route) => {
    const path = route.path === '/' ? (parentPath || '/') : `${parentPath}/${route.path || ''}`.replace(/\/+/g, '/');
    const current = route.element ? [{ ...route, path, children: undefined }] : [];
    return [...current, ...flattenPageRoutes(route.children || [], path === '/' ? '' : path)];
  });
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, portalRoot, '');
  const profileName = process.env.PORTAL_PROFILE || env.PORTAL_PROFILE || 'default';
  resolvePortalProfile(profileName);
  generateSelectedProfileModule(profileName);

  return {
    base: '/portal/',
    plugins: [
      react(),
      Pages({
        dirs: [{ dir: '.portal/pages', baseRoute: '' }],
        resolver: 'react',
        onRoutesGenerated: (routes) => flattenPageRoutes(routes),
      }),
      portalModuleGraphPlugin(),
    ],
    build: {
      target: ['chrome111', 'edge111', 'firefox114', 'safari16.4', 'ios16.4'],
    },
    server: {
      port: 9001,
      proxy: {
        '/api': {
          target: env.VITE_APP_BASE_URL || 'http://127.0.0.1/',
          changeOrigin: true,
        },
      },
    },
  };
});
