import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { composePortalProfile, type PortalProfile, type PortalRouteDefinition, type PortalRuntimeConfig } from '../app/kernel/feature';
import { portalKernelNavigation, portalKernelRoutes } from '../app/kernel/portalKernel';

const profileNamePattern = /^[a-z][a-z0-9-]*$/;
const profileName = process.env.PORTAL_PROFILE || 'default';
const portalRoot = resolve(import.meta.dirname, '..');
const generatedDirectory = resolve(portalRoot, '.portal');
const profileFile = resolve(portalRoot, 'app', 'profiles', `${profileName}.ts`);

if (!profileNamePattern.test(profileName)) {
  throw new Error(`PORTAL_PROFILE "${profileName}" 命名无效，必须使用 kebab-case`);
}
if (!existsSync(profileFile)) {
  throw new Error(`PORTAL_PROFILE "${profileName}" 不存在：${profileFile}`);
}

const profileModule = (await import(pathToFileURL(profileFile).href)) as { default?: PortalProfile };
if (!profileModule.default) throw new Error(`PORTAL_PROFILE "${profileName}" 缺少 default export`);

const composition = composePortalProfile(profileModule.default, {
  kernelRoutes: portalKernelRoutes,
  kernelNavigation: portalKernelNavigation,
});
const runtimeConfig: PortalRuntimeConfig = {
  profileId: composition.profile.id,
  site: composition.profile.site,
  featureIds: composition.featureIds,
  navigation: composition.navigation,
};
const selectedProfileSource = `// Generated by scripts/select-profile.ts. Do not edit.\nexport { default } from '../app/profiles/${profileName}';\n`;
const runtimeProfileSource = [
  '// Generated by scripts/select-profile.ts. Do not edit.',
  "import type { PortalRuntimeConfig } from '../app/kernel/feature';",
  `export const portalRuntime = Object.freeze(${JSON.stringify(runtimeConfig, null, 2)}) satisfies PortalRuntimeConfig;`,
  '',
].join('\n');

function writeWhenChanged(file: string, content: string): void {
  if (!existsSync(file) || readFileSync(file, 'utf8') !== content) writeFileSync(file, content, 'utf8');
}

function toPageFile(route: PortalRouteDefinition): string {
  if (route.index) return 'index.tsx';

  const segments = (route.path || '').split('/').map((segment) => {
    if (segment === '*') return '[...all]';
    return segment.startsWith(':') ? `[${segment.slice(1).replace(/\?$/, '')}]` : segment;
  });
  return `${segments.join('/')}.tsx`;
}

function generateProfilePages(routes: readonly PortalRouteDefinition[]): void {
  const pagesDirectory = resolve(generatedDirectory, 'pages');
  rmSync(pagesDirectory, { recursive: true, force: true });

  const writeRoute = (route: PortalRouteDefinition, parentPath = '') => {
    const outputFile = resolve(pagesDirectory, parentPath, toPageFile(route));
    const sourceFile = resolve(portalRoot, 'app', route.file);
    let importPath = relative(dirname(outputFile), sourceFile).replaceAll('\\', '/');
    if (!importPath.startsWith('.')) importPath = `./${importPath}`;

    mkdirSync(dirname(outputFile), { recursive: true });
    writeFileSync(outputFile, `// Generated by scripts/select-profile.ts. Do not edit.\nexport { default } from '${importPath}';\n`, 'utf8');

    const currentPath = route.index ? parentPath : `${parentPath}/${route.path || ''}`.replace(/^\/+/, '');
    for (const child of route.children || []) writeRoute(child, currentPath);
  };

  for (const route of routes) writeRoute(route);
}

mkdirSync(generatedDirectory, { recursive: true });
writeWhenChanged(resolve(generatedDirectory, 'selected-profile.ts'), selectedProfileSource);
writeWhenChanged(resolve(generatedDirectory, 'runtime-profile.ts'), runtimeProfileSource);
generateProfilePages(composition.routes);

for (const warning of composition.warnings) console.warn(`Portal profile warning: ${warning}`);
console.log(
  `Portal profile selected: ${composition.profile.id} (${composition.featureIds.length} features, ${composition.prerenderPaths.length} prerender paths)`,
);
