import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { composeH5Project } from '../src/platform/feature/compose';
import type { H5Registry, H5RouteDefinition } from '../src/platform/feature/types';
import { generatedRoot, getProjectFile, loadProject, resolveProjectId, toH5Relative } from './engineering-utils';

function toPageFile(route: H5RouteDefinition): string {
  const segments = route.path.slice(1).split('/').map((segment) => {
    if (segment === '*') return '[...all]';
    return segment.startsWith(':') ? `[${segment.slice(1).replace(/\?$/, '')}]` : segment;
  });
  return `${segments.join('/') || 'index'}.tsx`;
}

async function writePage(pagesRoot: string, file: string, source: string): Promise<void> {
  const output = path.join(pagesRoot, file);
  await mkdir(path.dirname(output), { recursive: true });
  await writeFile(output, `// Generated by scripts/select-project.ts. Do not edit.\n${source}`, 'utf8');
}

async function generateProjectPages(registry: H5Registry): Promise<void> {
  const pagesRoot = path.join(generatedRoot, 'pages');
  await rm(pagesRoot, { recursive: true, force: true });

  await writePage(pagesRoot, 'index.tsx', "import { Navigate } from 'react-router-dom';\nexport default function IndexPage() { return <Navigate to=\"/app\" replace />; }\n");
  const defaultRoute = registry.routeMap.get(registry.project.defaultRouteId);
  if (!defaultRoute) throw new Error(`默认路由 \"${registry.project.defaultRouteId}\" 未注册`);
  await writePage(pagesRoot, 'app/index.tsx', `import { Navigate } from 'react-router-dom';\nexport default function AppIndexPage() { return <Navigate to=\"${defaultRoute.path}\" replace />; }\n`);

  const pageExports = [
    ['login.tsx', 'src/pages/login/LoginPage.tsx', 'LoginPage'],
    ['401.tsx', 'src/pages/status/StatusPages.tsx', 'UnauthorizedPage'],
    ['403.tsx', 'src/pages/status/StatusPages.tsx', 'ForbiddenPage'],
    ['network-error.tsx', 'src/pages/status/StatusPages.tsx', 'NetworkErrorPage'],
    ['[...all].tsx', 'src/pages/status/StatusPages.tsx', 'NotFoundPage'],
  ] as const;
  for (const [file, target, exportName] of pageExports) {
    const output = path.join(pagesRoot, file);
    let importPath = path.relative(path.dirname(output), path.join(path.dirname(generatedRoot), target)).replaceAll(path.sep, '/');
    if (!importPath.startsWith('.')) importPath = `./${importPath}`;
    await writePage(pagesRoot, file, `export { ${exportName} as default } from '${importPath}';\n`);
  }

  for (const route of registry.routes) {
    const file = toPageFile(route);
    const output = path.join(pagesRoot, file);
    let importPath = path.relative(path.dirname(output), path.join(path.dirname(generatedRoot), 'src/app/FeatureRoutePage')).replaceAll(path.sep, '/');
    if (!importPath.startsWith('.')) importPath = `./${importPath}`;
    await writePage(
      pagesRoot,
      file,
      `import { FeatureRoutePage } from '${importPath}';\nexport default function GeneratedFeatureRoutePage() { return <FeatureRoutePage routeId=\"${route.id}\" />; }\n`,
    );
  }
}

const projectId = resolveProjectId(process.env.VITE_APP_PROJECT);
const project = await loadProject(projectId);
const registry = composeH5Project(project);
const selectionFile = path.join(generatedRoot, 'selected-project.json');
const selection = {
  schemaVersion: 1,
  projectId: registry.project.id,
  projectModule: toH5Relative(getProjectFile(projectId)),
  featureIds: registry.featureIds,
  routeIds: registry.routes.map((route) => route.id),
};

await mkdir(generatedRoot, { recursive: true });
await writeFile(selectionFile, `${JSON.stringify(selection, null, 2)}\n`, 'utf8');
await generateProjectPages(registry);

console.log(`[H5 Project] ${registry.project.id}: ${registry.featureIds.length} Features / ${registry.routes.length} Routes`);
