export { default as authTestApi } from './demo/authTest'
export { default as redisTestApi } from './demo/redisTest'
export { default as socketTaskTestApi } from './demo/socketTaskTest'
export { default as webSocketTaskTestApi } from './demo/webSocketTaskTest'
export { default as studentApi } from './demo/student'
export { default as treeApi } from './demo/tree'
